---
title: "ANU Students I am Working with that are Presenting at the JSM 2018"
date: "05-26-2018"
categories: [news, honours student, phd student]
---

I have three students presenting at the Joint Statistical Meeting (2018) in Vancouver:

* Mark Dawkins,Honours student (co-authors: Drs. Grace Chiu and Anton Westveld): **Melded Bayesian Inference for Stochastic Theoretical Models with Applications in Agent Based Modeling**
    - Monday, July 30, Speed Session (5 min oral presentation, then poster presentation).   
        + Sessions [166](http://ww2.amstat.org/meetings/jsm/2018/onlineprogram/ActivityDetails.cfm?SessionID=215816) & link[261](https://ww2.amstat.org/meetings/jsm/2018/onlineprogram/ActivityDetails.cfm?SessionID=215945)

---

* Swen Kuh,PhD student (co-authors: Drs. Grace Chiu and Anton Westveld): **Model-Based Socio-Economic Health Measures Using Causal Modeling**
    - Wednesday, August 1, Speed Session (5 min oral presentation, then poster presentation)
        + Sessions link[476](http://ww2.amstat.org/meetings/jsm/2018/onlineprogram/ActivityDetails.cfm?sessionid=215611) & link[539](http://ww2.amstat.org/meetings/jsm/2018/onlineprogram/ActivityDetails.cfm?sessionid=215611)
        
___

* Jaron Lee,Honours student (co-author: Dr. Anton Westveld): A Variational Bayes Approach to Clustered Latent Preference Models for Directed Network Data
   - Wednesday, August 1, Speed Session (5 min oral presentation, then poster presentation)
       + Sessions link[478](http://ww2.amstat.org/meetings/jsm/2018/onlineprogram/ActivityDetails.cfm?SessionID=215815) & link[540](http://ww2.amstat.org/meetings/jsm/2018/onlineprogram/ActivityDetails.cfm?SessionID=215815)